name: Publish Python distributions to TestPyPI

on: workflow_dispatch:

jobs:
    python-build-n-publish:
        name: Build and publish Python distribution
        runs-on: ubuntu-latest
        steps:
            - users: actions/checkout@main

            - name: Initialize Python 3.10
              uses: actions/setup-python@v1
              with:
                python-version: 3.10

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install flake8

            - name: Lint with flake8
              run: |
                # stop the build if there are Python syntam errors or undefined names
                flake8 . --count --select=E9, F63, F7, F82 --show-source --statistics
                # exit-zero treats all errors as warnings.
                flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

            - name: Build binary wheel and a source tarball
              run: python setup.py sdist

            - name: Publish distribution Test PyPI
              uses: pypa/gh-action-pypi-publish@master
              with:
                password: ${{ secrets.test_pypi_password }}
                repository_url: https://test.pypi.org/legacy/



name: Publish Python distributions to TestPyPI

on:
  workflow_dispatch:

jobs:
    python-build-n-publish:
        name: Build and publish Python distribution
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main

            - name: Initialize Pytho 3.9
              uses: actions/setup-python@v1
              with:
                python-version: 3.9

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install flake8

            - name: Lint with flake8
              run: |
                # stop the build if there are Python syntax errors or undefined names
                flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                # exit-zero treats all errors as warnings.
                flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

            - name: Build binary wheel and a source tarball
              run: python setup.py sdist

            - name: Publish distribution to TestPyPI
              uses: pypa/gh-action-pypi-publish@master
              with:
                password: ${{ secrets.test_bgmfast_password }}
                repository_url: https://test.pypi.org/legacy/
